plugins {
    id 'java'
    id 'org.springframework.boot' version '3.1.0' apply false
}

allprojects {
    group = 'com.aerodream'
    version = '1.0.0'
    sourceCompatibility = '17'

    repositories {
        mavenCentral()
    }
}

dependencies {
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

test {
    useJUnitPlatform()
}